### ISSUE TITLE
Hai sir I am got error while kernel compilation @realme-kernel-opensource

### ISSUE THREAD

**Issue by phhgsi** [realme-kernel-opensource/realme_12_plus_5g-AndroidU-kernel-source#2]
Can you specify which defconfig I am use for realme 12 pro + and where I am put the vendor tree 
......
@realme-kernel-opensource

**Comment by realme-kernel-opensource** [comment]
Please get the kernel source of realme 12 Pro+ form: https://github.com/realme-kernel-opensource/realme_12pro_plus-AndroidU-kernel-source & https://github.com/realme-kernel-opensource/realme_12pro_plus-AndroidU-vendor-source.

**Comment by phhgsi** [comment]
I am not ask about kernel source I am ask about which config defconfig I am use to build the kernel because using gki_defconfig gives error @realme-kernel-opensource

**Comment by realme-kernel-opensource** [comment]
[parrot_GKI.config](https://github.com/realme-kernel-opensource/realme_12pro_plus-AndroidU-kernel-source/blob/master/arch/arm64/configs/vendor/parrot_GKI.config)
